import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import Provider from "@/components/provider";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const vazir = Vazirmatn({ subsets: ["arabic", "latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${vazir.className} h-full antialiased`}
    >
      <body>
        <main className="max-w-3xl px-2 max-md:max-w-sm max-md:px-0.5 mx-auto">
          <Provider>{children}</Provider>
        </main>
      </body>
    </html>
  );
}
